"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Background from "@/components/Background/Background";
import MainLayout from "@/components/Layouts/MainLayout";
const inter = Inter({ subsets: ["latin"] });
import Music from "@/components/Music/Music";
import { useRef, useState } from "react";
import StartMusic from "@/components/Music/StartMusic";
import ControlMusic from "@/components/Music/ControlMusic";
import { GoogleAnalytics } from "@next/third-parties/google";
import OpenAI from "@/components/AIchat/OpenAI";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [audioStarted, setAudioStarted] = useState(false);

  const audioRef = useRef<HTMLAudioElement | null>(null);

  return (
    <html lang="en">
      <body className={inter.className}>
        <MainLayout>
          <div className="z-0">
            <Background />
          </div>

          <Music audioRef={audioRef} />
          {!audioStarted ? (
            <StartMusic
              audioRef={audioRef}
              audioStarted={audioStarted}
              setAudioStarted={setAudioStarted}
            />
          ) : (
            <>
              {<ControlMusic audioRef={audioRef} audioStarted={audioStarted} />}
              {children}
              <OpenAI />
            </>
          )}
          {/* <div className="z-10">{children}</div> */}
        </MainLayout>
      </body>
      <GoogleAnalytics gaId={`${process.env.ANALYTICS}`} />
    </html>
  );
}
