import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Chanu Wars",
  description: "Generated by create next app",
};

const MainLayout = ({ children }: { children: React.ReactNode }) => {
  return <main>{children}</main>;
};

export default MainLayout;
